version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD : 123456
  apache:
    build: ./apache-php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./webroot/:/var/www/ 
      - ./apache/logs/:/var/log/apache2/
    links:
      - "mysql"
