version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD : 123456
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
  apache:
    build: ./apache-php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./webroot/:/var/www/html/ 
      - ./apache-php/logs/:/var/log/apache2/
    links:
      - "mysql"
