version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "phpfpm"
    volumes:
      - ./webroot/:/var/www/html/
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./webroot/:/var/www/html/
    links:
      - "mysql"
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD : 123456
